# PANDAS

In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.DataFrame(np.random.randint(10,100,(5,5)),index=['r1','r2','r3','r4','r5'],columns=['c1','c2','c3','c4','c5'])

    c1  c2  c3  c4  c5
r1  16  82  87  95  85
r2  41  91  11  48  40
r3  69  60  98  69  94
r4  90  30  36  17  49
r5  37  48  70  43  54

In [4]:
df=pd.read_csv("D:\\Users\\abhisv\\Desktop\\DS\\application_test.csv")

In [5]:
df.shape# oly for rows and columns, use df.shape[0] and df.shape[1]

(48744, 121)

In [6]:
df.shape[1]

121

In [7]:
df.columns

Index(['SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR',
       'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT',
       'AMT_ANNUITY', 'AMT_GOODS_PRICE',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=121)

In [8]:
df.index

RangeIndex(start=0, stop=48744, step=1)

In [9]:
df.mean

<bound method DataFrame.mean of        SK_ID_CURR NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  \
0          100001         Cash loans           F            N               Y
1          100005         Cash loans           M            N               Y
2          100013         Cash loans           M            Y               Y
3          100028         Cash loans           F            N               Y
4          100038         Cash loans           M            Y               N
5          100042         Cash loans           F            Y               Y
6          100057         Cash loans           M            Y               Y
7          100065         Cash loans           M            N               Y
8          100066         Cash loans           F            N               Y
9          100067         Cash loans           F            Y               Y
10         100074         Cash loans           F            N               Y
11         100090         Cash loans           F            N               Y
12         100091         Cash loans           F            N               Y
13         100092         Cash loans           F            Y               Y
14         100106    Revolving loans           M            N               Y
15         100107         Cash loans           M            Y               Y
16         100109         Cash loans           F            Y               Y
17         100117         Cash loans           M            Y               Y
18         100128         Cash loans           F            Y               Y
19         100141         Cash loans           F            Y               Y
20         100150         Cash loans           F            N               Y
21         100168         Cash loans           F            N               Y
22         100169         Cash loans           F            N               Y
23         100170         Cash loans           M            N               Y
24         100171         Cash loans           M            Y               Y
25         100172         Cash loans           F            N               Y
26         100184         Cash loans           F            N               Y
27         100187         Cash loans           F            N               Y
28         100212         Cash loans           F            Y               N
29         100222         Cash loans           F            Y               Y
...           ...                ...         ...          ...             ...
48714      455963         Cash loans           F            N               N
48715      455965         Cash loans           M            Y               Y
48716      456007         Cash loans           M            N               Y
48717      456008         Cash loans           F            N               Y
48718      456009         Cash loans           F            N               Y
48719      456010         Cash loans           F            N               Y
48720      456011         Cash loans           F            Y               Y
48721      456013         Cash loans           F            N               Y
48722      456028         Cash loans           M            N               Y
48723      456058         Cash loans           F            N               N
48724      456111         Cash loans           F            N               Y
48725      456114         Cash loans           F            N               N
48726      456115         Cash loans           M            N               Y
48727      456116         Cash loans           F            N               N
48728      456119         Cash loans           F            N               Y
48729      456120         Cash loans           F            N               N
48730      456122         Cash loans           M            Y               N
48731      456123         Cash loans           F            Y               Y
48732      456166         Cash loans           F            N               Y
48733      456167         Cash loans           F            N               Y
48734      456168         Cash loans           F            N               Y
48735      456169         Cash loans           F            N               N
48736      456170         Cash loans           F            Y               Y
48737      456189         Cash loans           F            N               Y
48738      456202         Cash loans           F            Y               N
48739      456221         Cash loans           F            N               Y
48740      456222         Cash loans           F            N               N
48741      456223         Cash loans           F            Y               Y
48742      456224         Cash loans           M            N               N
48743      456250         Cash loans           F            Y               N

       CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0                 0          135000.0    568800.0      20560.5
1                 0           99000.0    222768.0      17370.0
2                 0          202500.0    663264.0      69777.0
3                 2          315000.0   1575000.0      49018.5
4                 1          180000.0    625500.0      32067.0
5                 0          270000.0    959688.0      34600.5
6                 2          180000.0    499221.0      22117.5
7                 0          166500.0    180000.0      14220.0
8                 0          315000.0    364896.0      28957.5
9                 1          162000.0     45000.0       5337.0
10                0           67500.0    675000.0      25447.5
11                0          135000.0    261621.0      16848.0
12                0          247500.0    296280.0      23539.5
13                0           90000.0    360000.0      18535.5
14                0          180000.0    157500.0       7875.0
15                0          180000.0    296280.0      21690.0
16                0          202500.0    407520.0      26041.5
17                0           90000.0    499221.0      22117.5
18                1          225000.0    431280.0      23526.0
19                0          175500.0    478498.5      46741.5
20                0           99000.0    225000.0      19242.0
21                0          157500.0    266652.0      16443.0
22                0          135000.0    540000.0      27702.0
23                1          337500.0   1313212.5      42493.5
24                0          157500.0    539100.0      29245.5
25                0           76500.0    225000.0      12334.5
26                0          112500.0    256032.0      10759.5
27                0          225000.0    501363.0      25726.5
28                0           90000.0    450000.0      23107.5
29                0          360000.0    945000.0      34074.0
...             ...               ...         ...          ...
48714             1          360000.0    547272.0      43366.5
48715             0          315000.0    900000.0      57519.0
48716             0          135000.0    318645.0      16398.0
48717             0           81000.0    180000.0      13455.0
48718             0          225000.0    360000.0      19530.0
48719             1          112500.0    690313.5      35374.5
48720             1          171000.0    323460.0      23134.5
48721             1          130500.0    468333.0      37129.5
48722             0          220500.0    166500.0      13284.0
48723             1           67500.0    315000.0      16213.5
48724             1          112500.0    514710.0      17707.5
48725             0           45000.0    450000.0      24543.0
48726             1          225000.0   1002339.0      37917.0
48727             1          180000.0    149256.0      15291.0
48728             0          247500.0    685386.0      38398.5
48729             2           81000.0    135000.0      16020.0
48730             2          157500.0    445095.0      40824.0
48731             0          112500.0    450000.0      28890.0
48732             0          189000.0    479700.0      54382.5
48733             0          135000.0   1047771.0      37764.0
48734             0          135000.0    835686.0      46660.5
48735             0           85500.0    109008.0       7411.5
48736             0          157500.0    500490.0      48888.0
48737             0          270000.0    360000.0      28570.5
48738             3          135000.0    252022.5      23112.0
48739             0          121500.0    412560.0      17473.5
48740             2          157500.0    622413.0      31909.5
48741             1          202500.0    315000.0      33205.5
48742             0          225000.0    450000.0      25128.0
48743             0          135000.0    312768.0      24709.5

       AMT_GOODS_PRICE  ... FLAG_DOCUMENT_18 FLAG_DOCUMENT_19  \
0             450000.0  ...                0                0
1             180000.0  ...                0                0
2             630000.0  ...                0                0
3            1575000.0  ...                0                0
4             625500.0  ...                0                0
5             810000.0  ...                0                0
6             373500.0  ...                0                0
7             180000.0  ...                0                0
8             315000.0  ...                0                0
9              45000.0  ...                0                0
10            675000.0  ...                0                0
11            216000.0  ...                0                0
12            225000.0  ...                0                0
13            360000.0  ...                0                0
14            157500.0  ...                0                0
15            225000.0  ...                0                0
16            360000.0  ...                0                0
17            373500.0  ...                0                0
18            360000.0  ...                0                0
19            454500.0  ...                0                0
20            225000.0  ...                0                0
21            202500.0  ...                0                0
22            540000.0  ...                0                0
23           1012500.0  ...                0                0
24            450000.0  ...                0                0
25            225000.0  ...                0                0
26            180000.0  ...                0                0
27            418500.0  ...                0                0
28            450000.0  ...                0                0
29            945000.0  ...                0                0
...                ...  ...              ...              ...
48714         495000.0  ...                0                0
48715         900000.0  ...                0                0
48716         216000.0  ...                0                0
48717         180000.0  ...                0                0
48718         360000.0  ...                0                0
48719         549000.0  ...                0                0
48720         270000.0  ...                0                0
48721         382500.0  ...                0                0
48722         166500.0  ...                0                0
48723         315000.0  ...                0                0
48724         387000.0  ...                0                0
48725         450000.0  ...                0                0
48726         846000.0  ...                0                0
48727         135000.0  ...                0                0
48728         585000.0  ...                0                0
48729         135000.0  ...                0                0
48730         405000.0  ...                0                0
48731         450000.0  ...                0                0
48732         450000.0  ...                0                0
48733         904500.0  ...                0                0
48734         765000.0  ...                0                0
48735          90000.0  ...                0                0
48736         450000.0  ...                0                0
48737         360000.0  ...                0                0
48738         217561.5  ...                0                0
48739         270000.0  ...                0                0
48740         495000.0  ...                0                0
48741         315000.0  ...                0                0
48742         450000.0  ...                0                0
48743         270000.0  ...                0                0

      FLAG_DOCUMENT_20 FLAG_DOCUMENT_21 AMT_REQ_CREDIT_BUREAU_HOUR  \
0                    0                0                        0.0
1                    0                0                        0.0
2                    0                0                        0.0
3                    0                0                        0.0
4                    0                0                        NaN
5                    0                0                        0.0
6                    0                0                        0.0
7                    0                0                        0.0
8                    0                0                        0.0
9                    0                0                        0.0
10                   0                0                        0.0
11                   0                0                        0.0
12                   0                0                        0.0
13                   0                0                        0.0
14                   0                0                        0.0
15                   0                0                        0.0
16                   0                0                        0.0
17                   0                0                        0.0
18                   0                0                        0.0
19                   0                0                        NaN
20                   0                0                        0.0
21                   0                0                        0.0
22                   0                0                        0.0
23                   0                0                        0.0
24                   0                0                        0.0
25                   0                0                        0.0
26                   0                0                        0.0
27                   0                0                        0.0
28                   0                0                        0.0
29                   0                0                        0.0
...                ...              ...                        ...
48714                0                0                        0.0
48715                0                0                        0.0
48716                0                0                        NaN
48717                0                0                        0.0
48718                0                0                        0.0
48719                0                0                        0.0
48720                0                0                        0.0
48721                0                0                        0.0
48722                0                0                        0.0
48723                0                0                        0.0
48724                0                0                        0.0
48725                0                0                        0.0
48726                0                0                        0.0
48727                0                0                        0.0
48728                0                0                        0.0
48729                0                0                        NaN
48730                0                0                        0.0
48731                0                0                        0.0
48732                0                0                        0.0
48733                0                0                        0.0
48734                0                0                        0.0
48735                0                0                        NaN
48736                0                0                        0.0
48737                0                0                        0.0
48738                0                0                        0.0
48739                0                0                        0.0
48740                0                0                        NaN
48741                0                0                        0.0
48742                0                0                        0.0
48743                0                0                        0.0

       AMT_REQ_CREDIT_BUREAU_DAY  AMT_REQ_CREDIT_BUREAU_WEEK  \
0                            0.0                         0.0
1                            0.0                         0.0
2                            0.0                         0.0
3                            0.0                         0.0
4                            NaN                         NaN
5                            0.0                         0.0
6                            0.0                         0.0
7                            0.0                         0.0
8                            0.0                         0.0
9                            0.0                         0.0
10                           0.0                         0.0
11                           0.0                         0.0
12                           0.0                         0.0
13                           0.0                         0.0
14                           0.0                         0.0
15                           0.0                         0.0
16                           0.0                         0.0
17                           0.0                         0.0
18                           0.0                         0.0
19                           NaN                         NaN
20                           0.0                         0.0
21                           0.0                         0.0
22                           0.0                         0.0
23                           0.0                         0.0
24                           0.0                         0.0
25                           0.0                         0.0
26                           0.0                         0.0
27                           0.0                         0.0
28                           0.0                         0.0
29                           0.0                         0.0
...                          ...                         ...
48714                        0.0                         0.0
48715                        0.0                         0.0
48716                        NaN                         NaN
48717                        0.0                         0.0
48718                        0.0                         0.0
48719                        0.0                         0.0
48720                        0.0                         0.0
48721                        0.0                         0.0
48722                        0.0                         0.0
48723                        0.0                         0.0
48724                        0.0                         0.0
48725                        0.0                         0.0
48726                        0.0                         0.0
48727                        0.0                         0.0
48728                        0.0                         0.0
48729                        NaN                         NaN
48730                        0.0                         0.0
48731                        0.0                         0.0
48732                        0.0                         0.0
48733                        0.0                         0.0

In [10]:
df.std()

SK_ID_CURR                     103169.547296
CNT_CHILDREN                        0.709047
AMT_INCOME_TOTAL               101522.591536
AMT_CREDIT                     365397.004174
AMT_ANNUITY                     16016.368315
AMT_GOODS_PRICE                336710.215040
REGION_POPULATION_RELATIVE          0.014428
DAYS_BIRTH                       4325.900393
DAYS_EMPLOYED                  144348.507136
DAYS_REGISTRATION                3552.612035
DAYS_ID_PUBLISH                  1569.276709
OWN_CAR_AGE                        11.462889
FLAG_MOBIL                          0.004529
FLAG_EMP_PHONE                      0.392526
FLAG_WORK_PHONE                     0.403488
FLAG_CONT_MOBILE                    0.039971
FLAG_PHONE                          0.440337
FLAG_EMAIL                          0.369046
CNT_FAM_MEMBERS                     0.890423
REGION_RATING_CLIENT                0.522694
REGION_RATING_CLIENT_W_CITY         0.515804
HOUR_APPR_PROCESS_START             3.278172
REG_REGION_NOT_LIVE_REGION          0.135937
REG_REGION_NOT_WORK_REGION          0.228306
LIVE_REGION_NOT_WORK_REGION         0.200673
REG_CITY_NOT_LIVE_CITY              0.267332
REG_CITY_NOT_WORK_CITY              0.417365
LIVE_CITY_NOT_WORK_CITY             0.379299
EXT_SOURCE_1                        0.205142
EXT_SOURCE_2                        0.181278
                                   ...
DEF_30_CNT_SOCIAL_CIRCLE            0.514413
OBS_60_CNT_SOCIAL_CIRCLE            3.580125
DEF_60_CNT_SOCIAL_CIRCLE            0.403791
DAYS_LAST_PHONE_CHANGE            878.920740
FLAG_DOCUMENT_2                     0.000000
FLAG_DOCUMENT_3                     0.409698
FLAG_DOCUMENT_4                     0.010128
FLAG_DOCUMENT_5                     0.120554
FLAG_DOCUMENT_6                     0.282536
FLAG_DOCUMENT_7                     0.006405
FLAG_DOCUMENT_8                     0.283969
FLAG_DOCUMENT_9                     0.066879
FLAG_DOCUMENT_10                    0.000000
FLAG_DOCUMENT_11                    0.034176
FLAG_DOCUMENT_12                    0.000000
FLAG_DOCUMENT_13                    0.000000
FLAG_DOCUMENT_14                    0.000000
FLAG_DOCUMENT_15                    0.000000
FLAG_DOCUMENT_16                    0.000000
FLAG_DOCUMENT_17                    0.000000
FLAG_DOCUMENT_18                    0.039456
FLAG_DOCUMENT_19                    0.000000
FLAG_DOCUMENT_20                    0.000000
FLAG_DOCUMENT_21                    0.000000
AMT_REQ_CREDIT_BUREAU_HOUR          0.046373
AMT_REQ_CREDIT_BUREAU_DAY           0.046132
AMT_REQ_CREDIT_BUREAU_WEEK          0.054037
AMT_REQ_CREDIT_BUREAU_MON           0.110924
AMT_REQ_CREDIT_BUREAU_QRT           0.693305
AMT_REQ_CREDIT_BUREAU_YEAR          1.838873
Length: 105, dtype: float64

In [11]:
df.var()

SK_ID_CURR                     1.064396e+10
CNT_CHILDREN                   5.027474e-01
AMT_INCOME_TOTAL               1.030684e+10
AMT_CREDIT                     1.335150e+11
AMT_ANNUITY                    2.565241e+08
AMT_GOODS_PRICE                1.133738e+11
REGION_POPULATION_RELATIVE     2.081728e-04
DAYS_BIRTH                     1.871341e+07
DAYS_EMPLOYED                  2.083649e+10
DAYS_REGISTRATION              1.262105e+07
DAYS_ID_PUBLISH                2.462629e+06
OWN_CAR_AGE                    1.313978e+02
FLAG_MOBIL                     2.051535e-05
FLAG_EMP_PHONE                 1.540766e-01
FLAG_WORK_PHONE                1.628025e-01
FLAG_CONT_MOBILE               1.597669e-03
FLAG_PHONE                     1.938965e-01
FLAG_EMAIL                     1.361948e-01
CNT_FAM_MEMBERS                7.928529e-01
REGION_RATING_CLIENT           2.732090e-01
REGION_RATING_CLIENT_W_CITY    2.660539e-01
HOUR_APPR_PROCESS_START        1.074641e+01
REG_REGION_NOT_LIVE_REGION     1.847878e-02
REG_REGION_NOT_WORK_REGION     5.212357e-02
LIVE_REGION_NOT_WORK_REGION    4.026975e-02
REG_CITY_NOT_LIVE_CITY         7.146644e-02
REG_CITY_NOT_WORK_CITY         1.741934e-01
LIVE_CITY_NOT_WORK_CITY        1.438679e-01
EXT_SOURCE_1                   4.208337e-02
EXT_SOURCE_2                   3.286176e-02
                                   ...
DEF_30_CNT_SOCIAL_CIRCLE       2.646205e-01
OBS_60_CNT_SOCIAL_CIRCLE       1.281729e+01
DEF_60_CNT_SOCIAL_CIRCLE       1.630473e-01
DAYS_LAST_PHONE_CHANGE         7.725017e+05
FLAG_DOCUMENT_2                0.000000e+00
FLAG_DOCUMENT_3                1.678525e-01
FLAG_DOCUMENT_4                1.025683e-04
FLAG_DOCUMENT_5                1.453325e-02
FLAG_DOCUMENT_6                7.982677e-02
FLAG_DOCUMENT_7                4.102985e-05
FLAG_DOCUMENT_8                8.063827e-02
FLAG_DOCUMENT_9                4.472767e-03
FLAG_DOCUMENT_10               0.000000e+00
FLAG_DOCUMENT_11               1.168031e-03
FLAG_DOCUMENT_12               0.000000e+00
FLAG_DOCUMENT_13               0.000000e+00
FLAG_DOCUMENT_14               0.000000e+00
FLAG_DOCUMENT_15               0.000000e+00
FLAG_DOCUMENT_16               0.000000e+00
FLAG_DOCUMENT_17               0.000000e+00
FLAG_DOCUMENT_18               1.556767e-03
FLAG_DOCUMENT_19               0.000000e+00
FLAG_DOCUMENT_20               0.000000e+00
FLAG_DOCUMENT_21               0.000000e+00
AMT_REQ_CREDIT_BUREAU_HOUR     2.150426e-03
AMT_REQ_CREDIT_BUREAU_DAY      2.128194e-03
AMT_REQ_CREDIT_BUREAU_WEEK     2.920043e-03
AMT_REQ_CREDIT_BUREAU_MON      1.230404e-02
AMT_REQ_CREDIT_BUREAU_QRT      4.806724e-01
AMT_REQ_CREDIT_BUREAU_YEAR     3.381453e+00
Length: 105, dtype: float64

In [12]:
df.corr()

,SK_ID_CURR,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
SK_ID_CURR,1.000000,0.000635,0.001278,0.005014,0.007112,0.005097,0.003324,0.002325,-0.000845,0.001032,...,-0.006286,NaN,NaN,NaN,-0.000307,0.001083,0.001178,0.000430,-0.002092,0.003457
CNT_CHILDREN,0.000635,1.000000,0.038962,0.027840,0.056770,0.025507,-0.015231,0.317877,-0.238319,0.175054,...,-0.000862,NaN,NaN,NaN,0.006362,0.001539,0.007523,-0.008337,0.029006,-0.039265
AMT_INCOME_TOTAL,0.001278,0.038962,1.000000,0.396572,0.457833,0.401995,0.199773,0.054400,-0.154619,0.067973,...,-0.006624,NaN,NaN,NaN,0.010227,0.004989,-0.002867,0.008691,0.007410,0.003281
AMT_CREDIT,0.005014,0.027840,0.396572,1.000000,0.777733,0.988056,0.135694,-0.046169,-0.083483,0.030740,...,-0.000197,NaN,NaN,NaN,-0.001092,0.004882,0.002904,-0.000156,-0.007750,-0.034533
AMT_ANNUITY,0.007112,0.056770,0.457833,0.777733,1.000000,0.787033,0.150864,0.047859,-0.137772,0.064450,...,-0.010762,NaN,NaN,NaN,0.008428,0.006681,0.003085,0.005695,0.012443,-0.044901
AMT_GOODS_PRICE,0.005097,0.025507,0.401995,0.988056,0.787033,1.000000,0.141453,-0.039308,-0.086425,0.033619,...,0.004489,NaN,NaN,NaN,-0.000671,0.004865,0.003358,-0.000254,-0.008490,-0.036227
REGION_POPULATION_RELATIVE,0.003324,-0.015231,0.199773,0.135694,0.150864,0.141453,1.000000,-0.033339,0.000209,-0.053130,...,0.013449,NaN,NaN,NaN,-0.001408,-0.011773,-0.008321,0.000105,-0.026650,0.001015
DAYS_BIRTH,0.002325,0.317877,0.054400,-0.046169,0.047859,-0.039308,-0.033339,1.000000,-0.637129,0.320174,...,0.030752,NaN,NaN,NaN,0.008861,-0.000386,0.012422,0.014094,0.088752,-0.095551
DAYS_EMPLOYED,-0.000845,-0.238319,-0.154619,-0.083483,-0.137772,-0.086425,0.000209,-0.637129,1.000000,-0.209123,...,-0.018859,NaN,NaN,NaN,-0.012991,-0.000785,-0.014058,-0.013891,-0.044351,0.064698
DAYS_REGISTRATION,0.001032,0.175054,0.067973,0.030740,0.064450,0.033619,-0.053130,0.320174,-0.209123,1.000000,...,0.008590,NaN,NaN,NaN,0.006212,-0.000152,0.008692,0.007414,0.046011,-0.036887
DAYS_ID_PUBLISH,-0.001722,-0.022586,0.030378,0.022273,0.050592,0.021095,-0.001972,0.263393,-0.280374,0.106100,...,0.021185,NaN,NaN,NaN,0.003148,0.003325,0.014009,0.011851,0.025928,-0.049065
OWN_CAR_AGE,-0.004995,0.003367,-0.141850,-0.099337,-0.101787,-0.109403,-0.094741,0.003875,0.035121,-0.026673,...,-0.007938,NaN,NaN,NaN,-0.009597,0.006166,0.009062,-0.005441,-0.002222,-0.017648
FLAG_MOBIL,-0.003414,0.002536,-0.002078,-0.010385,-0.007488,-0.011998,0.003522,0.006101,-0.009343,0.001297,...,0.000179,NaN,NaN,NaN,0.000220,0.000189,0.000250,0.000406,-0.003163,-0.002675
FLAG_EMP_PHONE,0.000842,0.239175,0.154005,0.082099,0.137381,0.085066,-0.000087,0.640946,-0.999830,0.211175,...,0.019156,NaN,NaN,NaN,0.013094,0.000914,0.014036,0.013875,0.045119,-0.064850
FLAG_WORK_PHONE,-0.002147,0.037734,-0.006639,-0.035827,-0.046307,-0.008161,-0.003336,0.195810,-0.245741,0.062912,...,0.077891,NaN,NaN,NaN,0.008170,0.001508,0.004917,0.001849,0.010255,-0.058626
FLAG_CONT_MOBILE,0.000159,-0.005813,-0.008058,0.024268,0.036500,0.020172,-0.004020,0.000612,-0.002891,-0.006730,...,0.001582,NaN,NaN,NaN,-0.011068,0.001538,0.002030,-0.007451,0.006962,0.008406
FLAG_PHONE,-0.002107,-0.030267,0.015788,0.016967,-0.005379,0.035244,0.114124,-0.036464,0.002153,-0.086200,...,0.023619,NaN,NaN,NaN,-0.001359,-0.006526,-0.002922,0.000134,-0.017054,-0.011943
FLAG_EMAIL,-0.001982,0.043839,0.106062,0.060994,0.075074,0.050875,0.017125,0.119079,-0.084444,0.043777,...,-0.014598,NaN,NaN,NaN,0.007164,0.003266,0.001754,0.001106,0.022846,0.008897
CNT_FAM_MEMBERS,-0.001637,0.877445,0.039884,0.092638,0.113028,0.092523,-0.016452,0.261650,-0.228601,0.166542,...,-0.003594,NaN,NaN,NaN,0.006731,0.002213,0.008430,-0.004184,0.020761,-0.027937
REGION_RATING_CLIENT,-0.008198,0.010157,-0.221804,-0.109085,-0.138137,-0.112240,-0.554430,0.011124,0.028118,0.074421,...,-0.005869,NaN,NaN,NaN,0.001355,0.000893,0.005206,-0.003225,0.024541,0.006283
REGION_RATING_CLIENT_W_CITY,-0.008349,0.008538,-0.242345,-0.123684,-0.156837,-0.124470,-0.550886,0.008646,0.032705,0.064313,...,-0.004997,NaN,NaN,NaN,0.000625,0.002806,0.003548,-0.003720,0.020217,0.006128
HOUR_APPR_PROCESS_START,0.004791,0.000781,0.070369,0.034668,0.034962,0.043311,0.159798,0.084400,-0.083665,-0.008862,...,0.003718,NaN,NaN,NaN,-0.020906,-0.008920,-0.011708,0.000622,0.002052,-0.025970
REG_REGION_NOT_LIVE_REGION,-0.001094,-0.014154,0.082567,0.021556,0.046346,0.023864,-0.019598,0.068396,-0.044324,0.032730,...,0.032776,NaN,NaN,NaN,-0.002365,-0.005298,-0.003733,-0.000254,0.010379,-0.027135
REG_REGION_NOT_WORK_REGION,0.004919,0.005364,0.160364,0.051678,0.091125,0.054084,0.047832,0.098476,-0.115920,0.042142,...,0.022336,NaN,NaN,NaN,0.002493,0.004087,0.001043,-0.000499,0.005724,-0.028815
LIVE_REGION_NOT_WORK_REGION,0.003884,0.013616,0.151170,0.050413,0.083857,0.052184,0.086842,0.069502,-0.100673,0.031121,...,0.004678,NaN,NaN,NaN,0.003153,0.007086,0.002253,-0.001639,0.001101,-0.020526
REG_CITY_NOT_LIVE_CITY,0.000166,0.012742,0.011326,-0.026030,0.002778,-0.024126,-0.055565,0.175246,-0.093055,0.067813,...,0.027449,NaN,NaN,NaN,0.008218,0.008205,-0.006411,0.000279,0.026977,-0.027434
REG_CITY_NOT_WORK_CITY,0.004968,0.061829,0.022296,-0.026393,0.011270,-0.025048,-0.041886,0.247187,-0.259119,0.100016,...,0.026070,NaN,NaN,NaN,0.007528,-0.002401,0.001871,-0.001245,0.024939,-0.028011
LIVE_CITY_NOT_WORK_CITY,0.007075,0.061120,0.025648,-0.010678,0.015952,-0.009775,-0.008636,0.167189,-0.221590,0.075910,...,0.009266,NaN,NaN,NaN,0.000695,-0.003020,0.005204,0.000398,0.015625,-0.019737
EXT_SOURCE_1,0.002718,-0.116490,0.090441,0.187027,0.103171,0.187950,0.093923,-0.522073,0.241218,-0.156420,...,-0.011278,NaN,NaN,NaN,-0.005182,-0.011837,-0.016308,-0.018408,-0.061106,0.020261
EXT_SOURCE_2,0.004941,-0.010491,0.150710,0.128013,0.116347,0.133482,0.219290,-0.117677,-0.003035,-0.066639,...,-0.010968,NaN,NaN,NaN,-0.004544,-0.017151,-0.001048,-0.010054,-0.039904,-0.004419
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DEF_30_CNT_SOCIAL_CIRCLE,-0.001528,-0.003574,-0.034529,-0.024448,-0.024346,-0.024274,-0.001020,-0.002880,0.021508,-0.002668,...,-0.003961,NaN,NaN,NaN,0.002124,-0.001050,-0.000934,0.001152,0.004631,0.023190
OBS_60_CNT_SOCIAL_CIRCLE,0.003685,0.004066,-0.026866,-0.004097,-0.011498,-0.004951,-0.013653,-0.004178,0.012443,-0.000946,...,-0.001615,NaN,NaN,NaN,0.004308,0.007623,-0.003343,-0.000842,-0.001521,0.022810
DEF_60_CNT_SOCIAL_CIRCLE,-0.000692,-0.001717,-0.038873,-0.026370,-0.028066,-0.025999,-0.004123,-0.001696,0.020867,0.001319,...,-0.004749,NaN,NaN,NaN,0.002502,-0.000970,-0.004277,-0.001610,0.004433,0.022410
DAYS_LAST_PHONE_CHANGE,-0.005536,0.001039,-0.060187,-0.104477,-0.042580,-0.107959,-0.050220,0.104960,0.032503,0.074601,...,0.023209,NaN,NaN,NaN,-0.004450,0.005146,0.002717,0.012356,0.069084,-0.093064
FLAG_DOCUMENT_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLAG_DOCUMENT_3,0.001888,0.074773,-0.063094,-0.004122,-0.014588,-0.007398,-0.101552,0.167079,-0.296940,0.038244,...,-0.075874,NaN,NaN,NaN,-0.003717,-0.008394,0.007561,0.001965,0.015290,0.004705
FLAG_DOCUMENT_4,0.006593,0.002899,-0.000652,-0.008536,-0.010809,-0.007635,0.008462,-0.001434,0.005375,-0.003261,...,-0.000400,NaN,NaN,NaN,-0.000381,-0.000328,-0.000432,-0.000703,0.005478,-0.001446
FLAG_DOCUMENT_5,-0.000586,-0.014996,0.010181,-0.000980,0.002911,-0.000299,0.026553,0.010693,-0.011227,-0.002043,...,-0.004835,NaN,NaN,NaN,0.007281,-0.000436,0.001084,0.004122,0.008773,-0.014380
FLAG_DOCUMENT_6,-0.005773,-0.149316,-0.099016,-0.053543,-0.085346,-0.059086,0.020771,-0.403049,0.584091,-0.126343,...,-0.012235,NaN,NaN,NaN,-0.006927,0.011252,-0.006769,-0.010267,-0.026330,0.046277
FLAG_DOCUMENT_7,-0.006610,0.000930,-0.001321,-0.005312,-0.007496,-0.004735,0.004632,-0.000637,0.005098,0.004246,...,-0.000253,NaN,NaN,NaN,-0.000311,-0.000268,-0.000353,-0.000574,0.004473,-0.005523
FLAG_DOCUMENT_8,0.003071,0.050427,0.173659,0.072205,0.130939,0.076600,0.095708,0.124355,-0.126805,0.058618,...,-0.012311,NaN,NaN,NaN,0.005452,-0.001418,-0.002287,0.003709,0.018031,-0.025820
FLAG_DOCUMENT_9,0.003946,-0.003874,0.049128,0.025121,0.036684,0.025758,0.041929,0.018868,-0.028651,0.010140,...,-0.002655,NaN,NaN,NaN,0.004989,0.005439,-0.003309,0.001232,-0.001961,-0.005415
FLAG_DOCUMENT_10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLAG_DOCUMENT_11,0.003054,-0.006461,-0.003945,0.000614,-0.010615,0.004276,0.010878,0.033619,-0.016180,0.009631,...,-0.001352,NaN,NaN,NaN,-0.001525,0.028990,-0.001730,0.003489,-0.016383,-0.025170
FLAG_DOCUMENT_12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLAG_DOCUMENT_13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLAG_DOCUMENT_14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLAG_DOCUMENT_15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLAG_DOCUMENT_16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLAG_DOCUMENT_17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLAG_DOCUMENT_18,-0.006286,-0.000862,-0.006624,-0.000197,-0.010762,0.004489,0.013449,0.030752,-0.018859,0.008590,...,1.000000,NaN,NaN,NaN,-0.001761,-0.001515,0.009205,-0.003248,-0.010480,-0.009864
FLAG_DOCUMENT_19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLAG_DOCUMENT_20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLAG_DOCUMENT_21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AMT_REQ_CREDIT_BUREAU_HOUR,-0.000307,0.006362,0.010227,-0.001092,0.008428,-0.000671,-0.001408,0.008861,-0.012991,0.006212,...,-0.001761,NaN,NaN,NaN,1.000000,0.151506,-0.002345,0.023510,-0.003075,0.011938
AMT_REQ_CREDIT_BUREAU_DAY,0.001083,0.001539,0.004989,0.004882,0.006681,0.004865,-0.011773,-0.000386,-0.000785,-0.000152,...,-0.001515,NaN,NaN,NaN,0.151506,1.000000,0.035567,0.005877,0.006509,0.002002
AMT_REQ_CREDIT_BUREAU_WEEK,0.001178,0.007523,-0.002867,0.002904,0.003085,0.003358,-0.008321,0.012422,-0.014058,0.008692,...,0.009205,NaN,NaN,NaN,-0.002345,0.035567,1.000000,0.054291,0.024957,-0.000252
AMT_REQ_CREDIT_BUREAU_MON,0.000430,-0.008337,0.008691,-0.000156,0.005695,-0.000254,0.000105,0.014094,-0.013891,0.007414,...,-0.003248,NaN,NaN,NaN,0.023510,0.005877,0.054291,1.000000,0.005446,0.026118
AMT_REQ_CREDIT_BUREAU_QRT,-0.002092,0.029006,0.007410,-0.007750,0.012443,-0.008490,-0.026650,0.088752,-0.044351,0.046011,...,-0.010480,NaN,NaN,NaN,-0.003075,0.006509,0.024957,0.005446,1.000000,-0.013081
AMT_REQ_CREDIT_BUREAU_YEAR,0.003457,-0.039265,0.003281,-0.034533,-0.044901,-0.036227,0.001015,-0.095551,0.064698,-0.036887,...,-0.009864,NaN,NaN,NaN,0.011938,0.002002,-0.000252,0.026118,-0.013081,1.000000

# House price advanced regression

In [13]:
import pandas as pd
df=pd.read_csv("D:\\house-prices-advanced-regression-techniques\\train.csv")# if we use r no need to use double slash

In [14]:
import os
os.chdir('D:\house-prices-advanced-regression-techniques')# setting my path to this folder so that can directly access the files inside the folder.

In [15]:
df=pd.read_csv('train.csv')

In [16]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000
10,11,20,RL,70.0,11200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,129500
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,New,Partial,345000
12,13,20,RL,NaN,12968,Pave,NaN,IR2,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,144000
13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,New,Partial,279500
14,15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2008,WD,Normal,157000
15,16,45,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,7,2007,WD,Normal,132000
16,17,20,RL,NaN,11241,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,700,3,2010,WD,Normal,149000
17,18,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,Shed,500,10,2006,WD,Normal,90000
18,19,20,RL,66.0,13695,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,159000
19,20,20,RL,70.0,7560,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2009,COD,Abnorml,139000
20,21,60,RL,101.0,14215,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,New,Partial,325300
21,22,45,RM,57.0,7449,Pave,Grvl,Reg,Bnk,AllPub,...,0,NaN,GdPrv,NaN,0,6,2007,WD,Normal,139400
22,23,20,RL,75.0,9742,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,230000
23,24,120,RM,44.0,4224,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,129900
24,25,20,RL,NaN,8246,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2010,WD,Normal,154000
25,26,20,RL,110.0,14230,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,256300
26,27,20,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,134800
27,28,20,RL,98.0,11478,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,306000
28,29,20,RL,47.0,16321,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2006,WD,Normal,207500
29,30,30,RM,60.0,6324,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,1431,60,RL,60.0,21930,Pave,NaN,IR3,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,192140
1431,1432,120,RL,NaN,4928,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,143750
1432,1433,30,RL,60.0,10800,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,64500
1433,1434,60,RL,93.0,10261,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,186500
1434,1435,20,RL,80.0,17400,Pave,NaN,Reg,Low,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,160000
1435,1436,20,RL,80.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,7,2008,COD,Abnorml,174000
1436,1437,20,RL,60.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2007,WD,Normal,120500
1437,1438,20,RL,96.0,12444,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2008,New,Partial,394617
1438,1439,20,RM,90.0,7407,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,4,2010,WD,Normal,149700
1439,1440,60,RL,80.0,11584,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,197000
1440,1441,70,RL,79.0,11526,Pave,NaN,IR1,Bnk,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,191000
1441,1442,120,RM,NaN,4426,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,149300
1442,1443,60,FV,85.0,11003,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,310000
1443,1444,30,RL,NaN,8854,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,121000
1444,1445,20,RL,63.0,8500,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,179600
1445,1446,85,RL,70.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,129000
1446,1447,20,RL,NaN,26142,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,157900
1447,1448,60,RL,80.0,10000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2007,WD,Normal,240000
1448,1449,50,RL,70.0,11767,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2007,WD,Normal,112000
1449,1450,180,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2006,WD,Abnorml,92000
1450,1451,90,RL,60.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2009,WD,Normal,136000
1451,1452,20,RL,78.0,9262,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,New,Partial,287090
1452,1453,180,RM,35.0,3675,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,145000
1453,1454,20,RL,90.0,17217,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Abnorml,84500
1454,1455,20,FV,62.0,7500,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,185000
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [17]:
df.head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500

In [18]:
df.tail(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [19]:
df.isna().sum() # count of null values in a columns

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType          8
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
                 ...
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
Length: 81, dtype: int64

In [20]:
(df.isna().sum()/df.shape[0])*100# calculating percentage of null values

Id                0.000000
MSSubClass        0.000000
MSZoning          0.000000
LotFrontage      17.739726
LotArea           0.000000
Street            0.000000
Alley            93.767123
LotShape          0.000000
LandContour       0.000000
Utilities         0.000000
LotConfig         0.000000
LandSlope         0.000000
Neighborhood      0.000000
Condition1        0.000000
Condition2        0.000000
BldgType          0.000000
HouseStyle        0.000000
OverallQual       0.000000
OverallCond       0.000000
YearBuilt         0.000000
YearRemodAdd      0.000000
RoofStyle         0.000000
RoofMatl          0.000000
Exterior1st       0.000000
Exterior2nd       0.000000
MasVnrType        0.547945
MasVnrArea        0.547945
ExterQual         0.000000
ExterCond         0.000000
Foundation        0.000000
                   ...
BedroomAbvGr      0.000000
KitchenAbvGr      0.000000
KitchenQual       0.000000
TotRmsAbvGrd      0.000000
Functional        0.000000
Fireplaces        0.000000
FireplaceQu      47.260274
GarageType        5.547945
GarageYrBlt       5.547945
GarageFinish      5.547945
GarageCars        0.000000
GarageArea        0.000000
GarageQual        5.547945
GarageCond        5.547945
PavedDrive        0.000000
WoodDeckSF        0.000000
OpenPorchSF       0.000000
EnclosedPorch     0.000000
3SsnPorch         0.000000
ScreenPorch       0.000000
PoolArea          0.000000
PoolQC           99.520548
Fence            80.753425
MiscFeature      96.301370
MiscVal           0.000000
MoSold            0.000000
YrSold            0.000000
SaleType          0.000000
SaleCondition     0.000000
SalePrice         0.000000
Length: 81, dtype: float64

In [21]:
((df.isna().sum()/df.shape[0])*100).head()

Id              0.000000
MSSubClass      0.000000
MSZoning        0.000000
LotFrontage    17.739726
LotArea         0.000000
dtype: float64

In [22]:
glob.glob("D:\\house-prices-advanced-regression-techniques\\*.csv")

NameError: name 'glob' is not defined

In [ ]:
import glob
for i in glob.glob("D:\\house-prices-advanced-regression-techniques\\*.csv"):
    df=pd.read_csv(i)
    print(i.split("\\")[-1],df.shape)

In [ ]:
import glob
for i in glob.glob("D:\\house-prices-advanced-regression-techniques\\*.csv"):
    df=pd.read_csv(i)
    print(i.split("\\")[-1],df.shape)
    print(20*'---')# for giving space
    print(df.isna().sum())
    print(20*'---')

In [ ]:
df.shape # gives last files shape

In [ ]:
df.columns[0:10]# show less output so it can be easily understood

In [ ]:
df[['MSSubClass','MSZoning']].head()

In [ ]:
df.columns

In [ ]:
len(df.columns)

In [ ]:
df.mean().index # getting numerical columns

In [ ]:
len(df.mean().index)

In [33]:
numerical=list(df.mean().index) #converting into list

In [34]:
numerical

['Id',
 'MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SalePrice']

In [35]:
cat=[]
for i in df.columns:
    if i not in numerical:
        cat.append(i)# getting the categorical columns and length

In [36]:
len(cat), len(numerical),len(df.columns)

(43, 38, 81)

In [37]:
df[cat].shape #total number of categorical columns

(1460, 43)

In [38]:
df[numerical].shape #total number of numerical columns

(1460, 38)

In [39]:
df[cat]['HouseStyle'].unique() # how many unique values are present

array(['2Story', '1Story', '1.5Fin', '1.5Unf', 'SFoyer', 'SLvl', '2.5Unf',
       '2.5Fin'], dtype=object)

In [40]:
df[cat]['HouseStyle'].nunique() #count of unique values

8

In [41]:
df[cat]['HouseStyle'].value_counts()# how many times each unique values as repeated

1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: HouseStyle, dtype: int64

In [42]:
numerical_class=[]
numerical_cont=[]
for i in df[numerical].columns:
    if df[i].nunique()<8:
        numerical_class.append(i)
    else:
        numerical_cont.append(i)
print(len(numerical),len(numerical_class),len(numerical_cont))

38 8 30

In [43]:
cat_class=[]
cat_cont=[]
for i in df[cat].columns:
    if df[i].nunique()<8:
        cat_class.append(i)
    else:
        cat_cont.append(i)
print(len(cat),len(cat_class),len(cat_cont))

43 35 8

In [44]:
print(len(df.columns))
print(len(cat),len(cat_class),len(cat_cont))
print(len(numerical),len(numerical_class),len(numerical_cont))

81
43 35 8
38 8 30

In [45]:
for i in df.columns:  #in each column how many unique values are present
    print(i,df[i].nunique())

Id 1460
MSSubClass 15
MSZoning 5
LotFrontage 110
LotArea 1073
Street 2
Alley 2
LotShape 4
LandContour 4
Utilities 2
LotConfig 5
LandSlope 3
Neighborhood 25
Condition1 9
Condition2 8
BldgType 5
HouseStyle 8
OverallQual 10
OverallCond 9
YearBuilt 112
YearRemodAdd 61
RoofStyle 6
RoofMatl 8
Exterior1st 15
Exterior2nd 16
MasVnrType 4
MasVnrArea 327
ExterQual 4
ExterCond 5
Foundation 6
BsmtQual 4
BsmtCond 4
BsmtExposure 4
BsmtFinType1 6
BsmtFinSF1 637
BsmtFinType2 6
BsmtFinSF2 144
BsmtUnfSF 780
TotalBsmtSF 721
Heating 6
HeatingQC 5
CentralAir 2
Electrical 5
1stFlrSF 753
2ndFlrSF 417
LowQualFinSF 24
GrLivArea 861
BsmtFullBath 4
BsmtHalfBath 3
FullBath 4
HalfBath 3
BedroomAbvGr 8
KitchenAbvGr 4
KitchenQual 4
TotRmsAbvGrd 12
Functional 7
Fireplaces 4
FireplaceQu 5
GarageType 6
GarageYrBlt 97
GarageFinish 3
GarageCars 5
GarageArea 441
GarageQual 5
GarageCond 5
PavedDrive 3
WoodDeckSF 274
OpenPorchSF 202
EnclosedPorch 120
3SsnPorch 20
ScreenPorch 76
PoolArea 8
PoolQC 3
Fence 4
MiscFeature 4
MiscVal 21
MoSold 12
YrSold 5
SaleType 9
SaleCondition 6
SalePrice 663

In [46]:
df[numerical_cont].shape

(1460, 30)

In [48]:
nullvalue_percentage=(df[numerical_cont].isna().sum()/df[numerical_cont].shape[0])*100

In [49]:
nullvalue_percentage[nullvalue_percentage>10]

LotFrontage    17.739726
dtype: float64

In [50]:
nullvalue_percentage[nullvalue_percentage>10].index

Index(['LotFrontage'], dtype='object')

In [51]:
nullvalue_percentage[nullvalue_percentage<10].index

Index(['Id', 'MSSubClass', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BedroomAbvGr', 'TotRmsAbvGrd', 'GarageYrBlt',
       'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'SalePrice'],
      dtype='object')

In [52]:
#Get dummies

In [53]:
df[cat_class].columns

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'BldgType', 'RoofStyle', 'MasVnrType',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu',
       'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive',
       'PoolQC', 'Fence', 'MiscFeature', 'SaleCondition'],
      dtype='object')

In [54]:
df[cat_class]['Alley'].unique()### need to be asked, have to do null treatment before get dummies.

array([nan, 'Grvl', 'Pave'], dtype=object)

In [58]:
df[cat_class].head(10).unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [130]:
pd.get_dummies(df[cat_class]['Alley']).head(10)

   Grvl  Pave
0     0     0
1     0     0
2     0     0
3     0     0
4     0     0
5     0     0
6     0     0
7     0     0
8     0     0
9     0     0

In [122]:
df[cat_class].shape

(1460, 35)

In [1]:
pd.get_dummies(df[cat_class]).head(10).shape

NameError: name 'pd' is not defined

In [90]:
df[cat_class]['MSZoning'].head(10)#using lable encoding

0    RL
1    RL
2    RL
3    RL
4    RL
5    RL
6    RL
7    RL
8    RM
9    RL
Name: MSZoning, dtype: object

In [91]:
df[cat_class]['MSZoning'].head(10).unique()

array(['RL', 'RM'], dtype=object)

In [92]:
df[cat_class]['MSZoning'].head(10)[1]

'RL'

In [93]:
x=[]
for i in df[cat_class]['MSZoning']:
    if i==df[cat_class]['MSZoning'].unique()[0]:
        x.append(0)
    elif i==df[cat_class]['MSZoning'].unique()[1]:
        x.append(1)
    elif i==df[cat_class]['MSZoning'].unique()[2]:
        x.append(2)
    elif i==df[cat_class]['MSZoning'].unique()[3]:
        x.append(3)
    else:
        x.append(4)

In [94]:
print(x)

[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 0, 0, 1, 1, 0, 0, 0, 3, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 3, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 1, 1, 1, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 3, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 3, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 3, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 3, 0, 0, 1, 0, 1, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1, 3, 0, 0, 0, 1, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 1, 3, 0, 1, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 4, 1, 1, 0, 0, 0, 3, 0, 0, 3, 0, 0, 0, 0, 1, 3, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 1, 0, 0, 0, 0, 4, 0, 0, 0, 0, 3, 3, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 3, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 3, 0, 0, 3, 0, 0, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 4, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3, 0, 1, 0, 0, 3, 0, 3, 0, 0, 0, 0, 1, 1, 0, 0, 4, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 3, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 4, 0, 0, 0, 4, 1, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 3, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 3, 1, 3, 0, 3, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 4, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 1, 4, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 3, 3, 0, 1, 1, 0, 0, 0, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 3, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 3, 0, 0, 0, 0, 0]

In [96]:
for i in df[numerical_cont].columns:
    df[i].fillna(df[i].median(),inplace=True)

In [100]:
df[numerical_cont].isna().sum()

Id               0
MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BedroomAbvGr     0
TotRmsAbvGrd     0
GarageYrBlt      0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
SalePrice        0
dtype: int64